### ISSUE TITLE
environment settings

### ISSUE THREAD

**Issue by SirHao** [uclasystem/Semeru#1]
Hi, i am trying to deploy semeru on my cluster, here are some questions:

1. the OS setting: _"Ubuntu 18.04 with MLNX 4.7"_ is not metioned in the following part of _Readme_ any more, so is that mean "Ubuntu 18.04 with MLNX 4.7"  is not recommend? or used in the _Memory-Server_ ？

2. Does _Semeru_ only support InﬁniBand NIC? Dose it support RoCEv2 NIC?

4. Is there any hareware requirement, like memory size, SSD capacity?

**Comment by wangchenxi7** [comment]
> 

Hi Sirhao,
Thanks for your interest in Semeru.

1. We didn't test this environment, Ubuntu 18.04 with MLNX 4.7. It may have some compatibility problems. You can have a try. If you encounter any problems, please feel free to inform us. 

2.  Yes. The implementation of Semeru only supports InfiniBand NIC for now. Because Semeru relies on the scatter/gather ability of InfiniBand. However, the design of Semeru applies to any RDMA networking. I encourage you to have a  try and report the problems to us. We will appreciate your contribution very much.  

3. It's better to confirm that the memory and SSD size is 1.5X the size of Java heap. Because the OS needs some memory to run its services.

**Comment by SirHao** [comment]
Thanks a lot!
